# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      include: "scope"
